blank_issues_enabled: true
contact_links:
  - name: "Support questions :speech_balloon:"
    url: https://invenio-talk.web.cern.ch/
    about: Find announcements, discussions, recipes and much more in the Invenio Talk forum.
  - name: "Report a security issue :rotating_light:"
    url: https://invenio.readthedocs.io/en/latest/community/security-policy.html#reporting-security-issues
    about: In case of a security issue, please follow the instructions in the documentation
  - name: "Propose a change to Invenio :memo:"
    url: https://github.com/inveniosoftware/rfcs/
    about: Would you like to propose a change to Invenio? RFC is what you are looking for!
